### ISSUE TITLE
syncthing-discosrv and syncthing-relaysrv outdated (v0.14.43-ds1)

### ISSUE THREAD

**Issue by cromefire** [syncthing/apt-web#10]
I don't know, if this is the bast place to report this, but the discovery and relay services are currently at `v0.14.43-ds1` while syncthing is at at `v0.14.49` and there were important changes.

**Comment by calmh** [comment]
v0.14.43-ds1 is a Debian packaged version, not something released by us.

However, I see that the versions on apt.syncthing.net are *also* outdated, which should be fixed.

**Comment by calmh** [comment]
v0.14.49 of discosrv/relaysrv is published to apt.syncthing.net

**Comment by cromefire** [comment]
Thanks, yes I didn't remove the `-ds1` thought that was clear
