### ISSUE TITLE
syncthing-discosrv and syncthing-relaysrv do not include systemd files

### ISSUE THREAD

**Issue by cromefire** [syncthing/apt-web#11]
The `syncthing-discosrv` and `syncthing-relaysrv` packages do not include the systemd `.service` files anymore, anyone who updates won't have service files anymore and the services won't be (re)started anymore.

**Comment by calmh** [comment]
Our packages have never had systemd service files in them. Perhaps they should, but that's a bug to be filed in the main repo I think, thanks.

**Comment by cromefire** [comment]
That's the previous version:
[syncthing-discosrv_0.14.43+ds1-6_amd64.deb.zip](https://github.com/syncthing/apt-web/files/2281074/syncthing-discosrv_0.14.43%2Bds1-6_amd64.deb.zip)

**Comment by calmh** [comment]
As I explained in your previous issue, `...-ds` packages are not from us, they are by Debian and hence from your distribution, not apt.s.n.

**Comment by cromefire** [comment]
Oh sorry I didn't realize that ubuntu already ships syncthing, sorry

**Comment by cromefire** [comment]
Ref syncthing/syncthing#5115
