### ISSUE TITLE
Convert apt.syncthing.net to HTTP or HTTPS

### ISSUE THREAD

**Issue by lps-rocks** [syncthing/apt-web#12]
Right now all traffic is forced to HTTPS on http://apt.syncthing.net - This is not necessary nor is it recommended - Especially if the repository requires SNI to serve the proper certificate since apt does not support SNI at the moment. 

Major repositories do not need to use HTTPS (see all Debian official repositories) - since any in-flight tampering would cause a GPG signing failure once the package is downloaded.

Also, at the bottom of the https://apt.syncthing.net/ homepage it says "If you insist, you can also use the above URLs with http instead of https." - That's not true.

```
* Rebuilt URL to: http://apt.syncthing.net/
*   Trying 82.196.13.137...
* TCP_NODELAY set
* Connected to apt.syncthing.net (82.196.13.137) port 80 (#0)
> GET / HTTP/1.1
> Host: apt.syncthing.net
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< Content-Type: text/html; charset=utf-8
< Location: https://apt.syncthing.net/
< Server: Caddy
< Date: Mon, 27 Aug 2018 06:24:31 GMT
< Content-Length: 61
< Connection: keep-alive
< 
<a href="https://apt.syncthing.net/">Moved Permanently</a>.
```

**Comment by calmh** [comment]
That's an oversight, it should allow HTTP as well for the package downloads. I disagree with HTTPS adding no value though; over plain HTTP it's trivial to for example serve old package lists and prevent upgrades fixing a security vulnerability.

**Comment by calmh** [comment]
Fixed; main page redirects to https (for browsers), dists and pool allow both http and https without prejudice.
