### ISSUE TITLE
syncthing-inotify outdated

### ISSUE THREAD

**Issue by imsodin** [syncthing/apt-web#9]
I have no idea whether this is the right place to report this, I guess here is as good as anywhere (?)
Syncthing-inotify is on 0.8.3 in the release, while the most recent version is 0.8.4 and ~it is not present at all in candidate~.
I didn't read the instructions on apt.syncthing.net accurately and replaced release with candidate instead of appending it. This confused me, as I considered it akin to debian's testing or unstable, which includes all releases (both testing and stable), but is fine - I should have just read the instructions.

And now 0.8.5 is in there - thanks.

**Comment by calmh** [comment]
Ah *here* was the ticket. I remember seeing something about this somewhere but then couldn't find it.
